### ISSUE TITLE
Cannot use client-side with React Native

### ISSUE THREAD

**Issue by joncursi** [ageitgey/node-unfluff#74]
After installing the module into my react native app, I get:

<img width="366" alt="screen shot 2017-04-27 at 12 50 23 pm" src="https://cloud.githubusercontent.com/assets/4974609/25494621/3b11cb7c-2b48-11e7-8b3b-de97cea020be.png">

I tried manually adding `fs` to package.json to make sure it's there in the module map, but same error. Is it possible to use this library client-side in an RN app?

**Comment by ageitgey** [comment]
No, this library only works server-side. 

However there are some open PRs that modify this library to work client-side like #68. I just haven't merged them because this library was never really designed to work client-side and requires data files that might be slow/too large to "bake in" to the code like that PR does.

**Comment by joncursi** [comment]
Okay, thank you for the info!

**Comment by JulianKingman** [comment]
@joncursi fs doesn't work on react native, did you try using this? https://github.com/itinance/react-native-fs
I think you'll have to modify references to `fs` and replace them with `react-native-fs`, but you could probably get it to work.
